version: '3'

services:
  bottleserver:
    build: service/
    ports:
      - 8080:8080
    networks:
      - deploy_network
    container_name: bottleserver

  streamlit:
    build: ui/
    depends_on:
      - bottleserver
    ports:
        - 8081:8081
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge
